# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import "../libcommon/fastlane/Fastfile"

gitlab_project_id = "5252730"

default_platform(:android)

platform :android do
  before_all do
    gradle(task: "clean")
  end

  lane :build_all do
    build_flavor(flavor: "")
  end

  lane :build_standard do |values|
    build_flavor(flavor: "standard")
  end

  lane :build_cheers do |values|
    build_flavor(flavor: "cheers")
  end

  lane :build_dollar do |values|
    build_flavor(flavor: "dollar")
  end

  lane :build_love do |values|
    build_flavor(flavor: "love")
  end

  lane :build_peace do |values|
    build_flavor(flavor: "peace")
  end

  lane :build_fortune_cookies do |values|
    build_flavor(flavor: "fortuneCookies")
  end

  desc "Deploy production (all flavors) to the Google Play"
  lane :deploy_all do
    deploy_standard
    deploy_cheers
    deploy_dollar
    deploy_love
    deploy_peace
    # deploy_fortune_cookies
  end

  desc "Deploy production (paid flavors) to the Google Play"
  lane :deploy_paid do
    deploy_cheers
    deploy_dollar
    deploy_love
    deploy_peace
  end

  desc "Deploy production 'standard' flavor to the Google Play"
  lane :deploy_standard do
    deploy_flavor(flavor: "standard")
  end

  desc "Deploy production 'cheers' flavor to the Google Play"
  lane :deploy_cheers do
    deploy_flavor(flavor: "cheers")
  end

  desc "Deploy production 'dollar' flavor to the Google Play"
  lane :deploy_dollar do
    deploy_flavor(flavor: "dollar")
  end

  desc "Deploy production 'love' flavor to the Google Play"
  lane :deploy_love do
    deploy_flavor(flavor: "love")
  end

  desc "Deploy production 'peace' flavor to the Google Play"
  lane :deploy_peace do
    deploy_flavor(flavor: "peace")
  end

  desc "Deploy production 'fortuneCookies' flavor to the Google Play"
  lane :deploy_fortune_cookies do
    deploy_flavor(flavor: "fortuneCookies")
  end

  lane :update_metadata_all do
    update_metadata_standard
    update_metadata_cheers
    update_metadata_dollar
    update_metadata_love
    update_metadata_peace
  end

  lane :update_metadata_standard do
    update_metadata_flavor(flavor: "standard")
  end

  lane :update_metadata_cheers do
    update_metadata_flavor(flavor: "cheers")
  end

  lane :update_metadata_dollar do
    update_metadata_flavor(flavor: "dollar")
  end

  lane :update_metadata_love do
    update_metadata_flavor(flavor: "love")
  end

  lane :update_metadata_peace do
    update_metadata_flavor(flavor: "peace")
  end

  desc "Fetch all metadata of apps"
  lane :fetch_metadata do
    update_metadata_flavor(flavor: "standard")
    update_metadata_flavor(flavor: "peace")
    update_metadata_flavor(flavor: "cheers")
    update_metadata_flavor(flavor: "love")
    update_metadata_flavor(flavor: "dollar")
  end

  lane :gitlab_release do |values|# only release standard release for now
    gitlab_release_for_project_id(project_id: gitlab_project_id, check_version: values[:check_version])
  end

end
